jobs:
  - name: spaceBar1
    type: runSh
    steps:
      - IN: sample-script
      - IN: triggertest1
      - IN: rsakey
      - IN: runimagein
      - TASK:
        - script: IN/sample-script/gitRepo/echo.sh

  - name: buildJob
    type: runSh
    steps:
      - IN: fiveOnethreefour
      - OUT: runimagein
      - TASK:
        - script: cd IN/fiveOnethreefour/gitRepo
        - script: echo "building..."
        - script: ls
        - script: docker build -t runimagein .
        - script: versionName="latest2" > /build/state/runimagein.env
