jobs:
  - name: lock_n_build_api
    type: runSh
    steps:
      - IN: teamParams
      - IN: configRepo
        switch: off
      - IN: apiRepo
      - TASK:
        - script: ./IN/configRepo/gitRepo/lockNload.sh pull
    on_success:
      - script: echo 'Locking everyone for good !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: lock_n_build_www
    type: runSh
    steps:
      - IN: teamParams
      - IN: configRepo
        switch: off
      - IN: wwwRepo
      - TASK:
        - script: ./IN/configRepo/gitRepo/lockNload.sh pull
    on_success:
      - script: echo 'Locking everyone for good !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: unlockJob
    type: runSh
    steps:
      - IN: configRepo
        switch: off
      - IN: teamParams
      - IN: intermediateJobs
      - TASK:
        - script: ./IN/configRepo/gitRepo/lockNload.sh push
    on_success:
      - script: echo 'Good Job on last commit !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: intermediateJobs
    type: runSh
    steps:
      - IN: buildApi
      - IN: buildWww
      - TASK:
        - script: echo "I'm the intermediateJobs"


  - name: buildApi
    type: runSh
    steps:
      - IN: lock_n_build_api
      - IN: apiRepo
        switch: off
      - TASK:
        - script: IN/apiRepo/gitRepo/echo.sh
        - script: cd IN
        - script: sudo apt-get install tree
        - script: tree
        - script: cat IN/apiRepo/integration.env
        
  - name: buildWww
    type: runSh
    steps:
      - IN: lock_n_build_www
      - IN: wwwRepo
        switch: off
      - TASK:
        - script: chmod +x IN/wwwRepo/gitRepo/echo.sh
        - script: IN/wwwRepo/gitRepo/echo.sh
