jobs:
  - name: spaceBar1
    type: runSh
    steps:
      - IN: sample-script
      - IN: triggertest1
      - IN: rsakey
      - IN: runImageIn
      - TASK:
        - script: IN/sample-script/gitRepo/echo.sh
