jobs:
  - name: lockJob
    type: runSh
    steps:
      - IN: teamParams
      - IN: configRepo
        switch: off
      - IN: apiRepo
      - IN: triggertest1
      - TASK:
        - script: ./IN/configRepo/gitRepo/lockNload.sh pull
    on_success:
      - script: echo 'Locking everyone for good !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: unlockJob
    type: runSh
    steps:
      - IN: configRepo
        switch: off
      - IN: teamParams
      - IN: buildJob
      - IN: triggertest1
      - TASK:
        - script: ./IN/configRepo/gitRepo/lockNload.sh push
    on_success:
      - script: echo 'Good Job on last commit !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
  # - name: rel-job
  #   type: release
  #   steps:
  #     - IN: runimagein
  #     - IN: version
  #     - TASK: managed
  #       bump: alpha

  - name: buildJob
    type: runSh
    steps:
      - IN: lockJob
      - IN: apiRepo
        switch: off
      - TASK:
        - script: IN/apiRepo/gitRepo/echo.sh
        - script: exit 1;
