jobs:
  - name: spaceBar1
    type: runSh
    steps:
      - IN: sample-script
      - IN: triggertest1
      - IN: rsakey
      - IN: runImageIn
      - TASK:
        - script: IN/sample-script/gitRepo/echo.sh

  - name: buildJob
    type: runSh
    steps:
      - IN: fiveOnethreefour
      - OUT: runImageIn
      - TASK:
        - script: cd IN/fiveOnethreefour/gitRepo
        - script: echo "building..."
        - script: ls
        - script: docker build -t=0 chetantarale/test:latest .
