jobs:
  - name: buildJob
    type: runSh
    steps:
      - IN: fiveOnethreefour
      - IN: shunit_test_runCI
      - OUT: runimagein
      - TASK:
        - script: ./IN/fiveOnethreefour/gitRepo/run.sh

  - name: rel-job
    type: release
    steps:
      - IN: runimagein
      - IN: version
      - TASK: managed
        bump: alpha

  - name: spaceBar1
    type: runSh
    steps:
      - IN: rel-job
      - IN: sample-script
      - IN: triggertest1
      - IN: rsakey
      - IN: runimagein
      - TASK:
        - script: IN/sample-script/gitRepo/echo.sh