jobs:
  - name: lockJob
    type: runSh
    steps:
      - IN: teamParams
      - IN: configRepo
        switch: off
      - IN: apiRepo
      - IN: wwwRepo
      - TASK:
        - script: ./IN/configRepo/gitRepo/lockNload.sh pull
    on_success:
      - script: echo 'Locking everyone for good !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: unlockJob
    type: runSh
    steps:
      - IN: configRepo
        switch: off
      - IN: teamParams
      - IN: buildApi
      - IN: buildWww
      - TASK:
        - script: ./IN/configRepo/gitRepo/lockNload.sh push
    on_success:
      - script: echo 'Good Job on last commit !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: buildApi
    type: runSh
    steps:
      - IN: lockJob
      - IN: apiRepo
        switch: off
      - TASK:
        - script: IN/apiRepo/gitRepo/echo.sh

  - name: buildWww
    type: runSh
    steps:
      - IN: lockJob
      - IN: wwwRepo
        switch: off
      - TASK:
        - script: chmod +x IN/wwwRepo/gitRepo/echo.sh
        - script: IN/wwwRepo/gitRepo/echo.sh
