jobs:
  - name: lockJob
    type: runSh
    steps:
      - IN: fiveOnethreefour
      - IN: sample-script
      - TASK:
        - script: "HELLO WORLD!" #./IN/fiveOnethreefour/gitRepo/run.sh
    on_success:
      - script: echo 'Locking everyone for good !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
  # - name: rel-job
  #   type: release
  #   steps:
  #     - IN: runimagein
  #     - IN: version
  #     - TASK: managed
  #       bump: alpha

  - name: buildJob
    type: runSh
    steps:
      - IN: lockJob
      - IN: sample-script
        switch: off
      - TASK:
        - script: echo "HELLO WORLD!" #IN/sample-script/gitRepo/echo.sh
